import logging
from typing import List, Dict
from datetime import datetime
from .schemas import HypothesisEvaluation

logger = logging.getLogger(__name__)

def find_missing_links(driver) -> List[Dict]:
    """
    Finds transitive relationships in the graph that are not directly connected.
    e.g., A -> B and B -> C exists, but A -> C does not.
    """
    with driver.session() as session:
        # Optimized query to find 2-hop relationships with evidence
        query = """
        MATCH (a:Entity)-[r1]->(b:Entity)-[r2]->(c:Entity)
        WHERE a <> c AND NOT (a)-[]->(c)
        RETURN 
            a.name AS source, 
            r1.evidence AS evidence1,
            b.name AS intermediate,
            r2.evidence AS evidence2,
            c.name AS target
        LIMIT 10
        """
        result = session.run(query)
        return [dict(record) for record in result]

def evaluate_hypothesis(hypothesis: Dict) -> HypothesisEvaluation:
    """
    Evaluates a transitive hypothesis found via graph traversal.
    All graph-derived transitive links are considered plausible candidates
    pending empirical validation.
    """
    reasoning = (
        f"{hypothesis['source']} may affect {hypothesis['target']} "
        f"via {hypothesis['intermediate']}. "
        f"Evidence chain: \"{hypothesis.get('evidence1', '')}\" → \"{hypothesis.get('evidence2', '')}\""
    )
    return HypothesisEvaluation(is_plausible=True, reasoning=reasoning)

def generate_markdown_report(topic: str, hypotheses: List[Dict]) -> str:
    """
    Generates a professional research report from found hypotheses, optimized for Obsidian.
    """
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # YAML Frontmatter for Obsidian
    report = f"""---
title: "Discovery Report: {topic}"
date: {date_str}
topic: "{topic}"
type: research_report
agent: VitaGraph Oracle v0.1.0
---

# ◈ Research Discovery: {topic}
**Generated by VitaGraph AI** | *{date_str}*

## 🧬 Executive Summary
The following novel biological relationships were identified through transitive link analysis of the Knowledge Graph. These represent potential discovery pathways where direct evidence is currently missing in the primary literature ingested.

---

"""
    
    if not hypotheses:
        report += "No novel transitive links were identified in this session. Try ingesting more varied literature to expand the discovery horizon."
        return report

    for i, h in enumerate(hypotheses, 1):
        # Use Wikilinks for Obsidian
        source = f"[[{h['source']}]]"
        intermediate = f"[[{h['intermediate']}]]"
        target = f"[[{h['target']}]]"
        
        report += f"### Discovery {i}: Potential {h['source']} → {h['target']} Link\n"
        report += f"**Proposed Relationship**: {source} --[Indirect]--> {target}\n\n"
        
        report += "#### 🧩 Evidence Chain\n"
        report += f"1.  **Step 1**: {source} is known to interact with **{intermediate}**.\n"
        report += f"    - *Evidence*: \"{h['evidence1']}\"\n"
        report += f"2.  **Step 2**: **{intermediate}** is known to interact with {target}.\n"
        report += f"    - *Evidence*: \"{h['evidence2']}\"\n\n"
        
        report += "#### 🧪 Hypothesis\n"
        report += f"Based on these findings, we hypothesize that {source} may exert a regulatory effect on {target} via the {intermediate} pathway. Further empirical validation is recommended.\n\n"
        report += "---\n\n"
        
    return report
